context:
  name: stransi
  version: "0.3.0"

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 2ba0195f935a8a152ad1921b25e14e7e78c549948d2ef0f63a6a5d9ab4625830

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=${{ python_min }}
    - ochre >=0.4.0,<1.0

tests:
  - python:
      imports:
      - stransi
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/getcuia/stransi
  summary: 'I see a \033[1;31mred\033[;39m door, and I want it painted \033[1;30mblack\033[;39m.'
  description: |
    stransi is a lightweight parser for ANSI escape code sequences.
    It implements a string-like type that is aware of its own ANSI escape sequences,
    and can be used to parse most of the common escape sequences used in terminal
    output manipulation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - claudiushaag
